theme: jekyll-theme-minimal

title: [Software Methods and Tools]
description: [This site layouts all of the resources for the course and helps you get everything setup for the semester.]

show_downloads: ["true"]
